name: Quality

on:
  merge_group:
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Style check
        run: gofmt -l .

      - name: Run Error finder
        run: go vet ./...

      - name: Run Tests
        run: go test ./...

      - name: Build
        run: go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t pillarbox-event-dispatcher .
