name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for semantic-release

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install semantic-release
        run: |
          npm install -g @semantic-release/commit-analyzer@12.0.0 \
          @semantic-release/release-notes-generator@13.0.0 \
          @semantic-release/exec@6.0.3 \
          @semantic-release/github@11.0.0 \
          semantic-release@23.1.1 \
          conventional-changelog-conventionalcommits@7.0.2

      - name: Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

      - name: Check version
        id: check_version
        run: >
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION)
            echo "Resolved version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version produced."
            echo "version=" >> $GITHUB_OUTPUT
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.version != ''  # Skip deploy if no version is set
    permissions:
      id-token: write
    env:
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GH_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/pillarbox-event-dispatcher:${{ needs.release.outputs.version }}
            ${{ env.ECR_REGISTRY }}/pillarbox-event-dispatcher:latest
